#!/usr/bin/env php
<?php

define( 'APP_DIR',   './releases/' );
define( 'APP_ALIAS', 'vendi-admin-cli.phar' );
define( 'APP_FILE',  APP_DIR . APP_ALIAS );

if( ! is_dir( APP_DIR ) )
{
    mkdir( APP_DIR );
}

if( is_file( APP_FILE ) )
{
    unlink( APP_FILE );
}

$phar = new \Phar( APP_FILE, 0, APP_ALIAS );
$phar->compressFiles( \Phar::GZ );
$phar->setSignatureAlgorithm( \Phar::SHA256 );
$files = array();
$files['app.php'] = './app.php';
$rd = new \RecursiveIteratorIterator( new \RecursiveDirectoryIterator( '.' ) );
foreach( $rd as $file )
{
    if( false !== strpos( $file->getPath(), '/tests' ) )
    {
        continue;
    }
    if( false !== strpos( $file->getPath(), '/.git' ) )
    {
        continue;
    }

    if ($file->getFilename() != '..' && $file->getFilename() != '.' && $file->getFilename() != __FILE__)
    {
        $files[substr($file->getPath().DIRECTORY_SEPARATOR.$file->getFilename(),2)]=$file->getPath().DIRECTORY_SEPARATOR.$file->getFilename();
    }
}
$phar->buildFromIterator(new ArrayIterator($files));
$phar->setStub( <<<EOB
#!/usr/bin/env php
<?php
Phar::mapPhar();
define( 'VENDI_CLI_ROOT_PHAR', 'phar://vendi-admin-cli.phar' );
include VENDI_CLI_ROOT_PHAR . '/app.php';
__HALT_COMPILER();
?>
EOB
);

$phar = null;
